services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
             - "80:80"
        #    - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts/default.conf:/etc/nginx/conf.d/default.conf
            - ./www:/var/www/
            - ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
        depends_on:
            - php

    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        container_name: php
        #image: php:8.1.4-fpm
        volumes:
            - ./www:/var/www
        links:
            - db
        depends_on:
            - db

    db:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
#            MYSQL_DATABASE: db_test



#mysql:
 #       image: mysql
  #      ports:
   #         - "3306:3306"
    #    volumes:
     #    - /etc/mysql:/etc/mysql
      #   - ./logs/mysql:/var/log/mysql
       #  - ./mysql:/var/lib/mysql
        # - ./mysql-files:/var/lib/mysql-files
        # - ./data:/docker-entrypoint-initdb.d
        # задаем пароль для root пользователя
        # заливку дампа сайта и создание пользователя для доступа к базе снаружи будем делать позже 
       # environment:
        #    MYSQL_ROOT_PASSWORD: password
         #   MYSQL_DATABASE: sait
